# Generated by Django 5.0.1 on 2024-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.CharField(max_length=100)),
                ('baslik', models.TextField(max_length=100)),
                ('aciklama', models.TextField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
