# Generated by Django 5.0.1 on 2024-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='media')),
                ('baslik', models.TextField(max_length=100)),
                ('aciklama', models.TextField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
