# Generated by Django 5.0.1 on 2024-01-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sliders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
