# Generated by Django 5.0.1 on 2024-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='resim',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
