# Generated by Django 5.0.1 on 2024-01-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sliders_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='media')),
                ('baslik', models.TextField(max_length=200)),
                ('aciklama', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='sliders',
            name='aciklama',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='resim',
            field=models.ImageField(upload_to='media'),
        ),
    ]
