# Generated by Django 5.0.1 on 2024-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_proje_alter_sliders_aciklama_alter_sliders_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='aciklama',
            field=models.TextField(max_length=1000),
        ),
    ]
