# Generated by Django 5.0.1 on 2024-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_proje_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField(max_length=100)),
                ('unvan', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yonetim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField(max_length=100)),
                ('unvan', models.TextField(max_length=100)),
            ],
        ),
    ]
